### ISSUE TITLE
Comandos sendo executados repetidamente

### ISSUE THREAD

**Issue by nathampa0909** [Neitan96/ClockSchedulerAPI#1]
Opa Neitan beleza? Ultimamente tenho percebido que está havendo algum bug, as vezes os comandos ocorrem antes do horário e ficam repetindo até dar o horário. Não tem nenhum erro, segue print:  http://image.prntscr.com/image/a15dd69a5a3341e9aebeb625210b5044.png

**Comment by Neitan96** [comment]
Poderia me passar as configurações dessa task?
tem outras tasks configuradas?
acontece somente com essa?
Obrigado
